trigger:
  branches:
    include:
    - master
    
resources:
- repo: self

pool:
  vmImage: 'Ubuntu 18.04'

steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/angular8

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build
    workingDir: src/angular8

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: angular8PipelineArtifactProd
    targetPath: 'src/angular8/dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src/angular8/dist'
    ArtifactName: angular8BuildArtifactProd

- task: DeleteFiles@1
  displayName: 'Delete Build files'
  inputs:
    Contents: 'src/angular8/dist'